services:
  postgres:
    image: postgres:13
    container_name: wishlist-pg-container
    environment:
      POSTGRES_DB: wishlist-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - wishlist-pg-data:/var/lib/postgresql/data

volumes:
  wishlist-pg-data:
