services:
  postgres-test:
    image: postgres:13
    container_name: wishlist-pg-test-container
    environment:
      POSTGRES_DB: test-wishlist-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - wishlist-pg-test-data:/var/lib/postgresql/data

volumes:
  wishlist-pg-test-data:
