spring:
  application.name: wishlist-app

  datasource:
    url: jdbc:postgresql://localhost:5432/wishlist-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.springframework.web: debug
